# Generated by Django 2.1.4 on 2019-03-01 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190228_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date order was made'),
            preserve_default=False,
        ),
    ]
