# Generated by Django 2.1.4 on 2019-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Unit price of the product', max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default='2.00', max_digits=9),
        ),
        migrations.AlterField(
            model_name='food',
            name='vat',
            field=models.DecimalField(decimal_places=2, default='0.36', max_digits=9),
        ),
    ]
