# Generated by Django 2.1.4 on 2019-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190303_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='vat',
            field=models.FloatField(default='0.36'),
        ),
    ]
