# Generated by Django 2.1.4 on 2019-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20190303_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default='2.00'),
        ),
    ]
