# Generated by Django 2.1.4 on 2019-03-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20190303_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash',
            field=models.FloatField(default='0.00'),
        ),
    ]
